version: '3.8'

services:
  mongo:
    image: mongo:latest 
    container_name: mongodb
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db 

  app:
    build: .
    container_name: my_app
    environment:
      - DATABASE_URL=${DATABASE_URL}  
      - DATABASE_NAME=${DATABASE_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
    depends_on:
      - mongo 
    ports:
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    user: "root"

volumes:
  mongo_data:
