# Use the official Python image from the Docker Hub
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Install pytest
RUN pip install pytest

# Run pytest when the container launches
CMD ["tail", "-f", "/dev/null"]

