name: Server CI/CD

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username:  ${{ secrets.DOCKER_USERNAME }}
        password:  ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image for leetcode-server
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/leetcode-server:latest . 

    - name: Push Docker image to Docker Hub for leetcode-server
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/leetcode-server:latest

    - name: Build Docker image for Java
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/java-server:latest -f tests-images/java/Dockerfile .

    - name: Push Docker image to Docker Hub for Java
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/java-server:latest

    - name: Build Docker image for Python
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/python-server:latest -f tests-images/python/Dockerfile .

    - name: Push Docker image to Docker Hub for Python
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/python-server:latest
